### PR TITLE
docs: Included Updates from Cheems and Fixed Styles

### PR DESCRIPTION
**Pull request by okawo80085**
Updates from Cheems and fixed styles for the overall theme

### CODE REVIEW

**Comment by okawo80085** [comment]
Altho it may be worth changing the logic by which the news on the home page is picked, maybe only show it if its newer than 3 months?

**Comment by okawo80085** [comment]
Nvm, not worth it, there is no good way to check the time or date apart from build time in jekyll, so we'd need to rebuild it anyway, easier to just update it by hand

**Comment by NAFOArt** [comment]
> Nvm, not worth it, there is no good way to check the time or date apart from build time in jekyll, so we'd need to rebuild it anyway, easier to just update it by hand

It could be done with a custom Liquid filter on the post metadata, but I am not sure custom filters work with the GitHub Pages version of Jekyll. They would have to be added to the _plugins directory and I _believe_ that's ignored by GitHub because they run Jekyll in safe mode.

Edit: on second thought, if we ever had custom GitHub Actions to publish the site, we could do whatever we wanted...

**Review by NAFOArt — CHANGES_REQUESTED** [review]
The `ButtonText` color has been deprecated in CSS and might cause issues in some browsers. Up to you if we should care or not :man_shrugging: 

[Further reading](https://www.w3.org/TR/css-color-3/#css-system)

**Comment by okawo80085** [comment]
Oh nah, i just forgot to change it, give me a sec

**Comment by okawo80085** [comment]
Fixed

**Review by NAFOArt — APPROVED** [review]

**Pull request merged**
